# Generated by Django 5.0 on 2023-12-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Null'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Incomplete')], default=False),
        ),
    ]
